name: Build Typst PDF

on:
  push:
    branches: [main, master]
    tags: ['v*']
  pull_request:
    branches: [main, master]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Typst
        uses: typst-community/setup-typst@v5
        # with:
        #   cache-dependency-path: |
        #     main.typ
        #     **/*.typ

      - name: Clone fonts repository
        run: git clone https://github.com/touying-typ/fonts.git fonts --depth=1

      - name: Compile Typst
        run: typst compile main.typ 信息论笔记.pdf --font-paths fonts

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: 信息论笔记        
          path: 信息论笔记.pdf    
          retention-days: 7

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: github.ref_type == 'tag'
        with:
          files: 信息论笔记.pdf   
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true